### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by SandipNagar** [jedisct1/sharedance#2]
Can you pls provide php 7 lib for this sharedance?

**Comment by jedisct1** [comment]
What doesn't work with PHP 7?

**Comment by SandipNagar** [comment]
yes does not work with php 7

**Comment by jedisct1** [comment]
But what exactly? The client part is written in PHP. What error do you get with that PHP code in PHP 7?

**Comment by SandipNagar** [comment]
I have followed the steps and given whatever persmission required but error I get this session_start(): Failed to read session data: user (path: /var/lib/php/session)

**Comment by jedisct1** [comment]
Maybe this helps? https://stackoverflow.com/questions/37901694/custom-session-handler-broken-with-php7-session-set-save-handler

**Comment by SandipNagar** [comment]
ok thanks, let me try

**Comment by jedisct1** [comment]
Maybe `ini_set('session.serialize_handler', 'php_serialize');` is all what is required.

**Comment by SandipNagar** [comment]
I did but not working.. can we check sharedanced service status using command?

**Comment by jedisct1** [comment]
Run it directly from the command line.

**Comment by SandipNagar** [comment]
i have used service sharedanced status, it shows unrecognized service, pls correct me if i am wrong

**Comment by jedisct1** [comment]
I don't know what that service command is. But you can run the server with something like `sharedanced -d /tmp`

**Comment by SandipNagar** [comment]
I tried this /usr/local/sbin/sharedanced --directory=/var/lib/php/session --daemonize,
One thing if you have sharedanced installed in your system then can you pls run command "service sharedance[d] status"

**Comment by jedisct1** [comment]
"service" returns "command not found" on my Mac.

But you can remove `--daemonize`. If the command-line prompt hangs, the server is working.

**Comment by SandipNagar** [comment]
can anyone help me out for the issue reported? thanks in advance

**Comment by jedisct1** [comment]
`ini_set('session.serialize_handler', 'php_serialize');` seemed to work for me. But I don't use PHP. You might have more success asking on a forum about PHP.
